class SetListItems {
  final String nameOfSet;
  final String abbreviation;

  SetListItems({required this.nameOfSet, required this.abbreviation});

  /*Not a complete list of sets*/
  List<SetListItems> setList = [
    SetListItems(nameOfSet: 'The List', abbreviation: 'PLST'),
    SetListItems(nameOfSet: 'Magic Online Promos', abbreviation: 'PRM'),
    SetListItems(nameOfSet: 'Secret Lair Drop', abbreviation: 'SLD'),
    SetListItems(nameOfSet: 'Doctor Who', abbreviation: 'WHO'),
    SetListItems(nameOfSet: 'Fallout', abbreviation: 'PIP'),
    SetListItems(nameOfSet: 'Commander Masters', abbreviation: 'CMM'),
    SetListItems(
        nameOfSet: 'Commander Legends: Battle for Baldur\'s Gate',
        abbreviation: 'CLB'),
    SetListItems(
        nameOfSet: 'The Lord of the Rings: Tales of Middle-earth',
        abbreviation: 'LTR'),
    SetListItems(nameOfSet: 'Jumpstart', abbreviation: 'J22'),
    SetListItems(nameOfSet: 'Foundations Jumpstart', abbreviation: 'J25'),
    SetListItems(nameOfSet: 'Salvat 2005', abbreviation: 'PSAL'),
    SetListItems(nameOfSet: 'Commander Legends', abbreviation: 'CMR'),
    SetListItems(nameOfSet: 'Eighth Edition', abbreviation: '8ED'),
    SetListItems(nameOfSet: 'Ninth Edition', abbreviation: '9ED'),
    SetListItems(nameOfSet: 'Seventh Edition', abbreviation: '7ED'),
    SetListItems(nameOfSet: 'Unfinity', abbreviation: 'UNF'),
    SetListItems(nameOfSet: 'Warhammer 40,000 Commander', abbreviation: '40K'),
    SetListItems(nameOfSet: 'Legacy Cube', abbreviation: 'LEGACY'),
    SetListItems(nameOfSet: 'Uncommon Cube', abbreviation: 'UNCOMMON'),
    SetListItems(nameOfSet: '30th Anniversary Edition', abbreviation: '30A'),
    SetListItems(
        nameOfSet: 'Tales of Middle-earth Commander', abbreviation: 'LTC'),
    SetListItems(nameOfSet: 'Double Masters 2022', abbreviation: '2X2'),
    SetListItems(nameOfSet: 'MTG Arena Cube', abbreviation: 'ARENA'),
    SetListItems(nameOfSet: 'Chromatic Cube', abbreviation: 'CHROMATIC'),
    SetListItems(nameOfSet: 'Grixis Cube', abbreviation: 'GRIXIS'),
    SetListItems(nameOfSet: 'Live the Dream', abbreviation: 'LIVETHEDREAM'),
    SetListItems(nameOfSet: 'Modern Cube', abbreviation: 'MODERN'),
    SetListItems(nameOfSet: 'Pro Tour Cube', abbreviation: 'PROTOUR'),
    SetListItems(nameOfSet: 'Tinkerer\'s Cube', abbreviation: 'TINKERER'),
    SetListItems(nameOfSet: 'Vintage Cube', abbreviation: 'VINTAGE'),
    SetListItems(nameOfSet: 'Twisted Color Cube', abbreviation: 'TWISTED'),
    SetListItems(nameOfSet: 'Innistrad: Double Feature', abbreviation: 'DBL'),
    SetListItems(nameOfSet: 'Kamigawa: Neon Dynasty', abbreviation: 'NEO'),
    SetListItems(nameOfSet: 'Ravnica Remastered', abbreviation: 'RVR'),
    SetListItems(nameOfSet: 'Modern Horizons 3', abbreviation: 'MH3'),
    SetListItems(nameOfSet: 'Streets of New Capenna', abbreviation: 'SNC'),
    SetListItems(nameOfSet: 'Tenth Edition', abbreviation: '10E'),
    SetListItems(nameOfSet: 'Jumpstart', abbreviation: 'JMP'),
    SetListItems(nameOfSet: 'Modern Horizons 2', abbreviation: 'MH2'),
    SetListItems(nameOfSet: 'Phyrexia: All Will Be One', abbreviation: 'ONE'),
    SetListItems(nameOfSet: 'Fifth Edition', abbreviation: '5ED'),
    SetListItems(nameOfSet: 'Dominaria Remastered', abbreviation: 'DMR'),
    SetListItems(nameOfSet: 'Dominaria United', abbreviation: 'DMU'),
    SetListItems(
        nameOfSet: 'March of the Machine Commander', abbreviation: 'MOC'),
    SetListItems(nameOfSet: 'Murders at Karlov Manor', abbreviation: 'MKM'),
    SetListItems(nameOfSet: 'New Capenna Commander', abbreviation: 'NCC'),
    SetListItems(
        nameOfSet: 'Alchemy Horizons: Baldur\'s Gate', abbreviation: 'HBG'),
    SetListItems(nameOfSet: 'Foundations', abbreviation: 'FDN'),
    SetListItems(nameOfSet: 'Kaldheim', abbreviation: 'KHM'),
    SetListItems(
        nameOfSet: 'Adventures in the Forgotten Realms', abbreviation: 'AFR'),
    SetListItems(nameOfSet: 'Innistrad: Crimson Vow', abbreviation: 'VOW'),
    SetListItems(nameOfSet: 'Duskmourn: House of Horro', abbreviation: 'DSK'),
    SetListItems(nameOfSet: 'The Lost Caverns of Ixalan', abbreviation: 'LCI'),
    SetListItems(nameOfSet: 'Time Spiral Remastered', abbreviation: 'TSR'),
    SetListItems(nameOfSet: 'Commander 2021', abbreviation: 'C21'),
    SetListItems(nameOfSet: 'Zendikar Risin', abbreviation: 'ZNR'),
    SetListItems(nameOfSet: 'Innistrad: Midnight Hunt', abbreviation: 'MID'),
    SetListItems(nameOfSet: 'The Brothers\' War', abbreviation: 'BRO'),
    SetListItems(nameOfSet: 'Throne of Eldraine', abbreviation: 'ELD'),
    SetListItems(nameOfSet: 'Modern Horizons 3 Commander', abbreviation: 'M3C'),
    SetListItems(nameOfSet: 'Bloomburrow', abbreviation: 'BLB'),
    SetListItems(nameOfSet: 'Core Set 2021', abbreviation: 'M21'),
    SetListItems(nameOfSet: 'Strixhaven: School of Mages', abbreviation: 'STX'),
    SetListItems(nameOfSet: 'Ikoria: Lair of Behemoths', abbreviation: 'IKO'),
    SetListItems(
        nameOfSet: 'Jumpstart: Historic Horizons', abbreviation: 'J21'),
    SetListItems(nameOfSet: 'March of the Machine', abbreviation: 'MOM'),
    SetListItems(nameOfSet: 'Mystery Booster 2', abbreviation: 'MB2'),
    SetListItems(nameOfSet: 'Double Masters', abbreviation: '2XM'),
    SetListItems(nameOfSet: 'Ice Age', abbreviation: 'ICE'),
    SetListItems(nameOfSet: 'Wilds of Eldraine', abbreviation: 'WOE'),
    SetListItems(nameOfSet: 'Fourth Edition', abbreviation: '4ED'),
    SetListItems(
        nameOfSet: 'Fourth Edition Foreign Black Border', abbreviation: '4BB'),
    SetListItems(nameOfSet: 'Outlaws of Thunder Junction', abbreviation: 'OTJ'),
    SetListItems(
        nameOfSet: 'Duskmourn: House of Horror Commander', abbreviation: 'DSC'),
    SetListItems(
        nameOfSet: 'The Lost Caverns of Ixalan Commander', abbreviation: 'LCC'),
    SetListItems(nameOfSet: 'Unknown Event', abbreviation: 'DA1'),
    SetListItems(
        nameOfSet: 'Murders at Karlov Manor Commander', abbreviation: 'MKC'),
    SetListItems(nameOfSet: 'Theros Beyond Death', abbreviation: 'THB'),
    SetListItems(nameOfSet: 'Bloomburrow Commander', abbreviation: 'BLC'),
    SetListItems(nameOfSet: 'Commander 2013', abbreviation: 'C13'),
    SetListItems(nameOfSet: 'Urza\'s Saga', abbreviation: 'USG'),
    SetListItems(nameOfSet: 'Invasion', abbreviation: 'INV'),
    SetListItems(nameOfSet: 'Mirage', abbreviation: 'MIR'),
    SetListItems(nameOfSet: 'Odyssey', abbreviation: 'ODY'),
    SetListItems(nameOfSet: 'Starter Commander Decks', abbreviation: 'SCD'),
    SetListItems(nameOfSet: 'Classic Sixth Edition', abbreviation: '6ED'),
    SetListItems(nameOfSet: 'Commander 2016', abbreviation: 'C16'),
    SetListItems(nameOfSet: 'Onslaught', abbreviation: 'ONS'),
    SetListItems(nameOfSet: 'Mercadian Masques', abbreviation: 'MMQ'),
    SetListItems(nameOfSet: 'Tempest', abbreviation: 'TMP'),
    SetListItems(nameOfSet: 'Core Set 2020', abbreviation: 'M20'),
    SetListItems(nameOfSet: 'Commander 2015', abbreviation: 'C15'),
    SetListItems(
        nameOfSet: 'Outlaws of Thunder Junction Commander',
        abbreviation: 'OTC'),
    SetListItems(nameOfSet: 'Amonkhet Remastered', abbreviation: 'AKR'),
    SetListItems(nameOfSet: 'Commander 2014', abbreviation: 'C14'),
    SetListItems(nameOfSet: 'Forgotten Realms Commander', abbreviation: 'AFC'),
    SetListItems(nameOfSet: 'Vintage Masters', abbreviation: 'VMA'),
    SetListItems(nameOfSet: 'Commander 2020', abbreviation: 'C20'),
    SetListItems(nameOfSet: 'Commander Anthology', abbreviation: 'CMA'),
    SetListItems(nameOfSet: 'Commander 2011', abbreviation: 'CMD'),
    SetListItems(nameOfSet: 'Core Set 2019', abbreviation: 'M19'),
    SetListItems(
        nameOfSet: 'Commander Anthology Volume 2', abbreviation: 'CM2'),
    SetListItems(nameOfSet: 'War or the Spark', abbreviation: 'WAR'),
    SetListItems(nameOfSet: 'Legends', abbreviation: 'LEG'),
    SetListItems(nameOfSet: 'Assassin\'s Creed', abbreviation: 'ACR'),
    SetListItems(nameOfSet: 'Commander 2017', abbreviation: 'C17'),
    SetListItems(nameOfSet: 'Pro Tour Collector Set', abbreviation: 'PTC'),
    SetListItems(nameOfSet: 'Champions of Kamigawa', abbreviation: 'CHK'),
    SetListItems(nameOfSet: 'Commander 2018', abbreviation: 'C18'),
    SetListItems(nameOfSet: 'Foreign Black Border', abbreviation: 'FBB'),
    SetListItems(nameOfSet: 'Mirrodin', abbreviation: 'MRD'),
    SetListItems(nameOfSet: 'Ravnica: City of Guilds', abbreviation: 'RAV'),
    SetListItems(nameOfSet: 'Revised Edition', abbreviation: '3ED'),
    SetListItems(nameOfSet: 'Summer Magic / Edgar', abbreviation: 'SUM'),
    SetListItems(nameOfSet: 'Collectors\' Edition', abbreviation: 'CED'),
    SetListItems(nameOfSet: 'Commander 2019', abbreviation: 'C19'),
    SetListItems(nameOfSet: 'Intl. Collectors\' Edition', abbreviation: 'CEI'),
    SetListItems(nameOfSet: 'Kaladesh Remastered', abbreviation: 'KLR'),
    SetListItems(nameOfSet: 'Limited Edition Beta', abbreviation: 'LEB'),
    SetListItems(nameOfSet: 'Shadowmoor', abbreviation: 'SHM'),
    SetListItems(nameOfSet: 'Shadows over Innistrad', abbreviation: 'SOI'),
    SetListItems(nameOfSet: 'Unlimited Edition', abbreviation: '2ED'),
    SetListItems(nameOfSet: 'Lorwyn', abbreviation: 'LRW'),
    SetListItems(nameOfSet: 'Time Spiral', abbreviation: 'TSP'),
    SetListItems(nameOfSet: 'Battle for Zendikar', abbreviation: 'BFZ'),
    SetListItems(nameOfSet: 'Limited Edition Alpha', abbreviation: 'LEA'),
    SetListItems(
        nameOfSet: 'Shadows over Innistrad Remastered', abbreviation: 'SIR'),
    SetListItems(nameOfSet: 'Khans of Tarkir', abbreviation: 'KTK'),
    SetListItems(nameOfSet: 'Ixalan', abbreviation: 'XLN'),
    SetListItems(nameOfSet: 'Magic Origins', abbreviation: 'ORI'),
    SetListItems(nameOfSet: 'Amonkhet', abbreviation: 'AKH'),
    SetListItems(nameOfSet: 'Magic 2015', abbreviation: 'M15'),
    SetListItems(nameOfSet: 'Ravnica: Clue Edition', abbreviation: 'CLU'),
    SetListItems(nameOfSet: 'Treasure Chest', abbreviation: 'PZ2'),
    SetListItems(nameOfSet: 'Dominaria', abbreviation: 'DOM'),
    SetListItems(nameOfSet: 'Kaladesh', abbreviation: 'KLD'),
    SetListItems(nameOfSet: 'Returns to Ravnica', abbreviation: 'RTR'),
    SetListItems(nameOfSet: 'Guilds of Ravnica', abbreviation: 'GRN'),
    SetListItems(nameOfSet: 'Ravnica Allegiance', abbreviation: 'RNR'),
    SetListItems(nameOfSet: 'Masters Edition 4', abbreviation: 'ME4'),
    SetListItems(nameOfSet: 'Tempest Remastered', abbreviation: 'TPR'),
    SetListItems(nameOfSet: 'Zendikar', abbreviation: 'ZEN'),
    SetListItems(nameOfSet: 'Unstable', abbreviation: 'UST'),
    SetListItems(nameOfSet: 'Dragons of Tarkir', abbreviation: 'DTK'),
    SetListItems(nameOfSet: 'Innistrad', abbreviation: 'ISD'),
    SetListItems(nameOfSet: 'Multiverse Legends', abbreviation: 'MUL'),
    SetListItems(nameOfSet: 'Portal', abbreviation: 'POR'),
    SetListItems(nameOfSet: 'Battlebond', abbreviation: 'BBD'),
    SetListItems(nameOfSet: 'Modern Horizons', abbreviation: 'MH1'),
    SetListItems(nameOfSet: 'Ultimate Masters', abbreviation: 'UMA'),
    SetListItems(nameOfSet: 'Shards of Alara', abbreviation: 'ALA'),
    SetListItems(nameOfSet: 'Eternal Masters', abbreviation: 'EMA'),
    SetListItems(nameOfSet: 'Gatecrash', abbreviation: 'GTC'),
    SetListItems(nameOfSet: 'Iconic Masters', abbreviation: 'IMA'),
    SetListItems(nameOfSet: 'Magic 2010', abbreviation: 'M10'),
    SetListItems(nameOfSet: 'Magic 2011', abbreviation: 'M11'),
    SetListItems(nameOfSet: 'Magic 2012', abbreviation: 'M12'),
    SetListItems(nameOfSet: 'Magic 2013', abbreviation: 'M13'),
    SetListItems(nameOfSet: 'Magic 2014', abbreviation: 'M14'),
    SetListItems(nameOfSet: 'Masters 25', abbreviation: 'A25'),
    SetListItems(nameOfSet: 'Modern Masters 2015', abbreviation: 'MM2'),
    SetListItems(nameOfSet: 'Modern Masters 2017', abbreviation: 'MM3'),
    SetListItems(nameOfSet: 'Scars of Mirrodin', abbreviation: 'SOM'),
    SetListItems(nameOfSet: 'Theros', abbreviation: 'THS'),
    SetListItems(nameOfSet: 'Rise of the Eldrazi', abbreviation: 'ROE'),
    SetListItems(nameOfSet: 'Masters Edition 2', abbreviation: 'ME2'),
    SetListItems(nameOfSet: 'Avacyn Restored', abbreviation: 'AVR'),
    SetListItems(
        nameOfSet: 'Adventures in the Forgotten Realms Promos',
        abbreviation: 'PAFR'),
    SetListItems(nameOfSet: 'Dominaria United Commander', abbreviation: 'DMC'),
    SetListItems(
        nameOfSet: 'March of the Machine: The Aftermath', abbreviation: 'MAT'),
    SetListItems(nameOfSet: 'Masters Edition 3', abbreviation: 'ME3'),
    SetListItems(nameOfSet: 'Modern Masters', abbreviation: 'MMA'),
    SetListItems(nameOfSet: 'Salvat 2011', abbreviation: 'PS11'),
    SetListItems(nameOfSet: 'Conspiracy: Take the Crown', abbreviation: 'CN2'),
    SetListItems(nameOfSet: 'Conspiracy', abbreviation: 'CNS'),
    SetListItems(nameOfSet: 'Hour of Devastation', abbreviation: 'HOU'),
    SetListItems(
        nameOfSet: 'The Brothers\' War Commander', abbreviation: 'BRC'),
    SetListItems(nameOfSet: 'Eldritch Moon', abbreviation: 'EMN'),
    SetListItems(nameOfSet: 'Rivals of Ixalan', abbreviation: 'RIX'),
    SetListItems(nameOfSet: 'Alliances', abbreviation: 'ALL'),
    SetListItems(nameOfSet: 'Aether Revolt', abbreviation: 'AER'),
    SetListItems(nameOfSet: 'Magic Online Theme Decks', abbreviation: 'TD0'),
    SetListItems(nameOfSet: 'Masters Edition', abbreviation: 'ME1'),
    SetListItems(nameOfSet: 'Fate Reforged', abbreviation: 'FRF'),
    SetListItems(
        nameOfSet: 'The Brothers\' War Retro Artifacts', abbreviation: 'BRR'),
    SetListItems(nameOfSet: 'Crimson Vow Commander', abbreviation: 'VOC'),
    SetListItems(nameOfSet: 'Fallen Empires', abbreviation: 'FEM'),
    SetListItems(nameOfSet: 'Midnight Hunt Commander', abbreviation: 'MIC'),
    SetListItems(nameOfSet: 'Oath of the Gatewatch', abbreviation: 'OGW'),
    SetListItems(nameOfSet: 'Dissension', abbreviation: 'DIS'),
    SetListItems(nameOfSet: 'Eventide', abbreviation: 'EVE'),
    SetListItems(nameOfSet: 'Future Sight', abbreviation: 'FUT'),
    SetListItems(
        nameOfSet: 'Murders at Karlov Manor Promos', abbreviation: 'PMKM'),
    SetListItems(nameOfSet: 'Portal Three Kindoms', abbreviation: 'PTK'),
    SetListItems(nameOfSet: 'Neon Dynasty Commander', abbreviation: 'NEC'),
    SetListItems(nameOfSet: 'New Phyrexia', abbreviation: 'NPH'),
    SetListItems(nameOfSet: 'War of the Spark Promos', abbreviation: 'PWAR'),
    SetListItems(
        nameOfSet: 'Phyrexia: All Will Be One Commander', abbreviation: 'ONC'),
    SetListItems(nameOfSet: 'Starter 1999', abbreviation: 'S99'),
    SetListItems(nameOfSet: 'Wilds of Eldraine Commander', abbreviation: 'WOC'),
    SetListItems(nameOfSet: 'The Brothers\' War Promos', abbreviation: 'PBRO'),
    SetListItems(nameOfSet: 'Planechase', abbreviation: 'HOP'),
    SetListItems(nameOfSet: 'Unhinged', abbreviation: 'UNH'),
    SetListItems(nameOfSet: 'Guildpact', abbreviation: 'GPT'),
    SetListItems(nameOfSet: 'Visions', abbreviation: 'VIS'),
    SetListItems(nameOfSet: 'Weatherlight', abbreviation: 'WTH'),
    SetListItems(nameOfSet: 'Betrayers of Kamigawa', abbreviation: 'BOK'),
    SetListItems(nameOfSet: 'Born of the Gods', abbreviation: 'BNG'),
    SetListItems(nameOfSet: 'Darksteel', abbreviation: 'DST'),
    SetListItems(nameOfSet: 'Fifth Dawn', abbreviation: '5DN'),
    SetListItems(nameOfSet: 'Journey into Nyx', abbreviation: 'JOU'),
    SetListItems(nameOfSet: 'Planar Chaos', abbreviation: 'PLC'),
    SetListItems(nameOfSet: 'Portal Second Age', abbreviation: 'P02'),
    SetListItems(nameOfSet: 'Saviors of Kamigawa', abbreviation: 'SOK'),
    SetListItems(
        nameOfSet: 'Strixhaven: School of Mages Promos', abbreviation: 'PSTX'),
    SetListItems(
        nameOfSet: 'Modern Horizons 2 Art Series', abbreviation: 'AMH2'),
    SetListItems(nameOfSet: 'Strixhaven Art Series', abbreviation: 'ASTX'),
    SetListItems(nameOfSet: 'Bloomburrow Promos', abbreviation: 'PBLB'),
    SetListItems(nameOfSet: 'Dominaria United Promos', abbreviation: 'PDMU'),
    SetListItems(
        nameOfSet: 'Duskmourn: House of Horror Promos', abbreviation: 'PDSK'),
    SetListItems(
        nameOfSet: 'Outlaws of Thunder Junction Promos', abbreviation: 'POTJ'),
    SetListItems(
        nameOfSet: 'Phyrexia: All Will Be One Promos', abbreviation: 'PONE'),
    SetListItems(
        nameOfSet: 'Streets of New Capenna Promos', abbreviation: 'PSNC'),
    SetListItems(nameOfSet: 'Wilds of Eldraine Promos', abbreviation: 'PWOE'),
    SetListItems(nameOfSet: 'Dark Ascension', abbreviation: 'DKA'),
    SetListItems(nameOfSet: 'Dragon\'s Maze', abbreviation: 'DGM'),
    SetListItems(nameOfSet: 'Planechase 2012', abbreviation: 'PC2'),
    SetListItems(nameOfSet: 'Planechase Anthology', abbreviation: 'PCA'),
    SetListItems(nameOfSet: 'Coldsnap', abbreviation: 'CSP'),
    SetListItems(nameOfSet: 'Mirrodin Besieged', abbreviation: 'MBS'),
    SetListItems(
        nameOfSet: 'The Lost Caverns of Ixalan Promos', abbreviation: 'PLCI'),
    SetListItems(nameOfSet: 'Kaldheim Promos', abbreviation: 'PKHM'),
    SetListItems(
        nameOfSet: 'World Championship Decks 2002', abbreviation: 'WC02'),
    SetListItems(
        nameOfSet: 'Innistrad: Midnight Hunt Promos', abbreviation: 'PMID'),
    SetListItems(nameOfSet: 'Zendikar Rising Promos', abbreviation: 'PZNR'),
    SetListItems(nameOfSet: 'Archenemy', abbreviation: 'ARC'),
    SetListItems(nameOfSet: 'Morningtide', abbreviation: 'MOR'),
    SetListItems(nameOfSet: 'Legendary Cube Prize Pack', abbreviation: 'PZ1'),
    SetListItems(
        nameOfSet: 'Kamigawa: Neon Dynasty Promos', abbreviation: 'PNEO'),
    SetListItems(nameOfSet: 'Planeshift', abbreviation: 'PLS'),
    SetListItems(nameOfSet: 'Alara Reborn', abbreviation: 'ARB'),
    SetListItems(nameOfSet: 'Conflux', abbreviation: 'CON'),
    SetListItems(nameOfSet: 'Legions', abbreviation: 'LGN'),
    SetListItems(nameOfSet: 'Worldwake', abbreviation: 'WWK'),
    SetListItems(nameOfSet: 'Prophecy', abbreviation: 'PCY'),
    SetListItems(nameOfSet: 'Apocalypse', abbreviation: 'APC'),
    SetListItems(nameOfSet: 'Core Set 2020 Promos', abbreviation: 'PM20'),
    SetListItems(nameOfSet: 'Exodus', abbreviation: 'EXO'),
    SetListItems(nameOfSet: 'Judgment', abbreviation: 'JUD'),
    SetListItems(nameOfSet: 'Nemesis', abbreviation: 'NEM'),
    SetListItems(nameOfSet: 'Scourge', abbreviation: 'SCG'),
    SetListItems(nameOfSet: 'Stronghold', abbreviation: 'STH'),
    SetListItems(nameOfSet: 'Torment', abbreviation: 'TOR'),
    SetListItems(nameOfSet: 'Urza\'s Destiny', abbreviation: 'UDS'),
    SetListItems(nameOfSet: 'Urza\'s Legacy', abbreviation: 'ULG'),
    SetListItems(
        nameOfSet: 'World Championship Decks 2003', abbreviation: 'WC03'),
    SetListItems(nameOfSet: 'Zendikar Risin Commander', abbreviation: 'ZNC'),
    SetListItems(nameOfSet: 'Homelands', abbreviation: 'HML'),
    SetListItems(
        nameOfSet: 'World Championship Decks 2001', abbreviation: 'WC01'),
    SetListItems(nameOfSet: 'Battle Royale Box Set', abbreviation: 'BRB'),
    SetListItems(nameOfSet: 'Core Set 2021 Promos', abbreviation: 'PM21'),
    SetListItems(
        nameOfSet: 'Ikoria: Lair of Behemoths Promos', abbreviation: 'PIKO'),
    SetListItems(nameOfSet: 'Theros Beyond Death Promos', abbreviation: 'PTHB'),
    SetListItems(nameOfSet: 'Throne of Eldraine Promos', abbreviation: 'PELD'),
    SetListItems(nameOfSet: 'Game Night: Free-for-All', abbreviation: 'GN3'),
    SetListItems(
        nameOfSet: 'March of the Machine Promos', abbreviation: 'PMOM'),
    SetListItems(nameOfSet: 'RNA Guild Kit', abbreviation: 'GK2'),
    SetListItems(
        nameOfSet: 'World Championship Decks 1997', abbreviation: 'WC97'),
    SetListItems(nameOfSet: 'GRN Guild Kit', abbreviation: 'GK1'),
    SetListItems(nameOfSet: 'Strixhaven Mystical Archive', abbreviation: 'STA'),
    SetListItems(nameOfSet: 'Chronicles', abbreviation: 'CHR'),
    SetListItems(
        nameOfSet: 'Chronicles Foreign Black Border', abbreviation: 'BCHR'),
    SetListItems(nameOfSet: 'Renaissance', abbreviation: 'REN'),
    SetListItems(nameOfSet: 'The Dark', abbreviation: 'DRK'),
    SetListItems(
        nameOfSet: 'Mystery Booster Playtest Cards 2019', abbreviation: 'CMB1'),
    SetListItems(
        nameOfSet: 'Mystery Booster Playtest Cards 2021', abbreviation: 'CMB2'),
    SetListItems(nameOfSet: 'Time Spiral Timeshifted', abbreviation: 'TSB'),
    SetListItems(nameOfSet: 'Arena Beginner Set', abbreviation: 'ANB'),
    SetListItems(nameOfSet: 'Ixalan Promos', abbreviation: 'PXLN'),
    SetListItems(nameOfSet: 'Kaldheim Commander', abbreviation: 'KHC'),
    SetListItems(nameOfSet: 'Dominaria Promos', abbreviation: 'PDOM'),
    SetListItems(
        nameOfSet: 'World Championship Deck 1998', abbreviation: 'WC98'),
    SetListItems(
        nameOfSet: 'World Championship Deck 2000', abbreviation: 'WC00'),
    SetListItems(nameOfSet: 'Duels of the Planeswalkers', abbreviation: 'DPA'),
    SetListItems(
        nameOfSet: 'Innistrad: Crimson Vow Promos', abbreviation: 'PVOW'),
    SetListItems(
        nameOfSet: 'World Championship Deck 1999', abbreviation: 'WC99'),
    SetListItems(nameOfSet: 'Archenemy: Nicol Bolas', abbreviation: 'E01'),
    SetListItems(
        nameOfSet: 'Battle for Baldur\'s Gate Promos', abbreviation: 'PCLB'),
    SetListItems(
        nameOfSet: 'Wilds of Eldraine: Enchating Tales', abbreviation: 'WOT'),
    SetListItems(
        nameOfSet: 'World Championship Decks 2004', abbreviation: 'WC04'),
    SetListItems(nameOfSet: 'Antiquities', abbreviation: 'ATQ')
  ];
}
